// <auto-generated />
using CW03.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CW03.Migrations
{
    [DbContext(typeof(CW03Context))]
    partial class CW03ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CW03.Models.BookmarkEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BookmarkType")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ReadOnly")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("BookmarkEntity");

                    b.HasDiscriminator<string>("Discriminator").HasValue("BookmarkEntity");
                });

            modelBuilder.Entity("CW03.Models.Folder", b =>
                {
                    b.HasBaseType("CW03.Models.BookmarkEntity");

                    b.HasDiscriminator().HasValue("Folder");
                });

            modelBuilder.Entity("CW03.Models.Item", b =>
                {
                    b.HasBaseType("CW03.Models.BookmarkEntity");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Item");
                });

            modelBuilder.Entity("CW03.Models.ItemLink", b =>
                {
                    b.HasBaseType("CW03.Models.Item");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("ItemLink");
                });

            modelBuilder.Entity("CW03.Models.ItemLocation", b =>
                {
                    b.HasBaseType("CW03.Models.Item");

                    b.HasDiscriminator().HasValue("ItemLocation");
                });

            modelBuilder.Entity("CW03.Models.ItemTextFile", b =>
                {
                    b.HasBaseType("CW03.Models.Item");

                    b.HasDiscriminator().HasValue("ItemTextFile");
                });
#pragma warning restore 612, 618
        }
    }
}
